In [1]:
# importing librarys
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,StandardScaler
from collections import Counter
# importing all lib...
import numpy as np
import pandas as pd
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer
from pandas_ml import ConfusionMatrix

In [2]:
train_data = pd.read_csv('kddtrain.csv')
test_data = pd.read_csv('kddtest.csv')
len(train_data), len(test_data)

(494021, 311029)

In [3]:
train_data.tail(10)

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
494011,0,tcp,http,SF,308,662,0,0,0,0,...,255,1.0,0.0,0.03,0.06,0.00,0.01,0.0,0.0,Normal
494012,0,tcp,http,SF,291,1862,0,0,0,0,...,255,1.0,0.0,0.02,0.05,0.00,0.01,0.0,0.0,Normal
494013,0,tcp,http,SF,289,244,0,0,0,0,...,255,1.0,0.0,0.02,0.05,0.00,0.01,0.0,0.0,Normal
494014,0,tcp,http,SF,306,662,0,0,0,0,...,255,1.0,0.0,0.02,0.05,0.00,0.01,0.0,0.0,Normal
494015,0,tcp,http,SF,289,1862,0,0,0,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,Normal
494016,0,tcp,http,SF,310,1881,0,0,0,0,...,255,1.0,0.0,0.01,0.05,0.00,0.01,0.0,0.0,Normal
494017,0,tcp,http,SF,282,2286,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,Normal
494018,0,tcp,http,SF,203,1200,0,0,0,0,...,255,1.0,0.0,0.06,0.05,0.06,0.01,0.0,0.0,Normal
494019,0,tcp,http,SF,291,1200,0,0,0,0,...,255,1.0,0.0,0.04,0.05,0.04,0.01,0.0,0.0,Normal
494020,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.00,0.01,0.0,0.0,Normal

In [4]:
test_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,Normal
1,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,Normal
2,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,Normal
3,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.00,0.0,0.0,0.0,0.0,0.0,R2L
4,0,udp,private,SF,105,146,0,0,0,0,...,254,1.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,R2L

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494021 entries, 0 to 494020
Data columns (total 42 columns):
duration                       494021 non-null int64
protocol_type                  494021 non-null object
service                        494021 non-null object
flag                           494021 non-null object
src_bytes                      494021 non-null int64
dst_bytes                      494021 non-null int64
land                           494021 non-null int64
wrong_fragment                 494021 non-null int64
Urgent                         494021 non-null int64
Hot                            494021 non-null int64
num_failed_logins              494021 non-null int64
logged_in                      494021 non-null int64
num_compromised                494021 non-null int64
root_shell                     494021 non-null int64
su_attempted                   494021 non-null int64
num_root                       494021 non-null int64
num_file_creations             494021 non-null int64
num_shells                     494021 non-null int64
num_access_files               494021 non-null int64
num_outbound_cmds              494021 non-null int64
is_host_login                  494021 non-null int64
is_guest_login                 494021 non-null int64
count                          494021 non-null int64
srv_count                      494021 non-null int64
serror_rate                    494021 non-null float64
srv_serror_rate                494021 non-null float64
rerror_rate                    494021 non-null float64
srv_rerror_rate                494021 non-null float64
same_srv_rate                  494021 non-null float64
diff_srv_rate                  494021 non-null float64
srv_diff_host_rate             494021 non-null float64
dst_host_count                 494021 non-null int64
dst_host_srv_count             494021 non-null int64
dst_host_same_srv_rate         494021 non-null float64
dst_host_diff_srv_rate         494021 non-null float64
dst_host_same_src_port_rate    494021 non-null float64
dst_host_srv_diff_host_rate    494021 non-null float64
dst_host_serror_rate           494021 non-null float64
dst_host_srv_serror_rate       494021 non-null float64
dst_host_rerror_rate           494021 non-null float64
dst_host_srv_rerror_rate       494021 non-null float64
class                          494021 non-null object
dtypes: float64(15), int64(23), object(4)
memory usage: 158.3+ MB

In [6]:
test_data.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,num_failed_logins,logged_in,num_compromised,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,311029.000000,3.110290e+05,3.110290e+05,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,...,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000,311029.000000
mean,17.902736,1.731702e+03,7.479937e+02,0.000029,0.000762,0.000051,0.014677,0.002363,0.172476,0.011243,...,235.282681,199.193914,0.793494,0.024953,0.547919,0.004566,0.058764,0.058791,0.142659,0.141693
std,407.644400,1.276567e+05,1.612018e+04,0.005379,0.040367,0.009821,0.312068,0.049990,0.377794,1.958325,...,60.913298,100.306470,0.387090,0.096003,0.491963,0.035773,0.231296,0.232997,0.344380,0.346573
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.050000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,244.000000,0.970000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,5.200000e+02,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,255.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.032000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,255.000000,1.000000,0.010000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,57715.000000,6.282565e+07,5.203179e+06,1.000000,3.000000,3.000000,101.000000,4.000000,1.000000,796.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
y_train = train_data.iloc[:]['class']
x_train = train_data.iloc[:,:-1]
# test
y_test = test_data.iloc[:]['class']
x_test = test_data.iloc[:,:-1]

In [8]:
# [   0 :  7  ] --> 0,1,2,3,4,5,6

In [9]:
len(x_train), len(x_test)

(494021, 311029)

In [10]:
y_test.unique()

array(['Normal', 'R2L', 'DOS', 'PROBE', 'U2R'], dtype=object)

In [11]:
Counter(y_train)

Counter({'Normal': 97278,
         'U2R': 52,
         'DOS': 391458,
         'R2L': 1126,
         'PROBE': 4107})

In [12]:
x_train = pd.DataFrame({col: x_train[col].astype('category').cat.codes for col in x_train}, index=x_train.index)
x_test = pd.DataFrame({col: x_test[col].astype('category').cat.codes for col in x_test}, index=x_test.index)

In [13]:
len(x_train), len(x_test)

(494021, 311029)

In [14]:
x_test.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
0,0,2,46,9,94,126,0,0,0,0,...,255,254,100,1,0,0,0,0,0,0
1,0,2,46,9,94,126,0,0,0,0,...,255,254,100,1,0,0,0,0,0,0
2,0,2,46,9,94,126,0,0,0,0,...,255,254,100,1,0,0,0,0,0,0
3,0,2,46,9,94,126,0,0,0,0,...,255,254,100,1,0,0,0,0,0,0
4,0,2,46,9,94,126,0,0,0,0,...,255,254,100,1,1,0,0,0,0,0

In [15]:
y_train.head(10)

0    Normal
1    Normal
2    Normal
3    Normal
4    Normal
5    Normal
6    Normal
7    Normal
8    Normal
9    Normal
Name: class, dtype: object

In [16]:
label_encoder = LabelEncoder()
fit_train = label_encoder.fit_transform(y_train)
y_train = pd.DataFrame( fit_train, index=y_train.index, columns=['class'] )
#test
fit_test = label_encoder.fit_transform(y_test)
y_test = pd.DataFrame( fit_test, index=y_test.index, columns=['class'] )

In [17]:
y_train.nunique() # from 0 to 4 --> 5 class

class    5
dtype: int64

In [18]:
y_test.nunique() # from 0 to 4 --> 5 class

class    5
dtype: int64

In [19]:
y_test.head()

   class
0      1
1      1
2      1
3      3
4      3

In [20]:
y_train.head()

   class
0      1
1      1
2      1
3      1
4      1

In [21]:
scaler_train = StandardScaler()
scaler_data_train = scaler_train.fit_transform(x_train)
#test
scaler_test = StandardScaler()
scaler_data_test = scaler_test.fit_transform(x_test)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int8, int16 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int8, int16 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int8, int16 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int8, int16 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [22]:
x_train = pd.DataFrame(data = scaler_data_train, index=x_train.index, columns=x_train.columns)
#test
x_test = pd.DataFrame(data = scaler_data_test, index=x_test.index, columns=x_test.columns)

In [23]:
x_train.tail()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
494016,-0.090604,0.925753,-0.104067,0.514274,-0.600693,1.113549,-0.006673,-0.048834,-0.002571,-0.049029,...,-2.262261,0.625558,0.599396,-0.282867,-1.229844,1.196724,-0.464438,-0.426441,-0.25204,-0.249464
494017,-0.090604,0.925753,-0.104067,0.514274,-0.656248,1.409373,-0.006673,-0.048834,-0.002571,-0.049029,...,-3.497871,0.625558,0.599396,-0.282867,-0.897417,1.196724,-0.464438,-0.426441,-0.25204,-0.249464
494018,-0.090604,0.925753,-0.104067,0.514274,-0.812990,0.610351,-0.006673,-0.048834,-0.002571,-0.049029,...,-3.343420,0.625558,0.599396,-0.282867,-1.125961,1.196724,-0.305196,-0.426441,-0.25204,-0.249464
494019,-0.090604,0.925753,-0.104067,0.514274,-0.638391,0.610351,-0.006673,-0.048834,-0.002571,-0.049029,...,-3.188969,0.625558,0.599396,-0.282867,-1.167514,1.196724,-0.358277,-0.426441,-0.25204,-0.249464
494020,-0.090604,0.925753,-0.104067,0.514274,-0.781245,0.635622,-0.006673,-0.048834,-0.002571,-0.049029,...,-3.497871,0.625558,0.599396,-0.282867,-0.897417,1.196724,-0.464438,-0.426441,-0.25204,-0.249464

In [24]:
x_test.tail()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,Urgent,Hot,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
311024,-0.078388,2.232618,1.428547,0.47954,-0.917815,-0.188427,-0.005379,-0.020505,-0.005238,-0.064965,...,0.323695,0.556357,0.533484,-0.259915,-1.093415,-0.1623,-0.254146,-0.252326,-0.414249,-0.408892
311025,-0.078388,2.232618,1.428547,0.47954,-0.917815,-0.188427,-0.005379,-0.020505,-0.005238,-0.064965,...,0.323695,0.556357,0.533484,-0.259915,-1.093415,-0.1623,-0.254146,-0.252326,-0.414249,-0.408892
311026,-0.078388,2.232618,1.428547,0.47954,-0.917815,-0.188427,-0.005379,-0.020505,-0.005238,-0.064965,...,0.323695,0.556357,0.533484,-0.259915,-1.093415,-0.1623,-0.254146,-0.252326,-0.414249,-0.408892
311027,-0.078388,2.232618,1.428547,0.47954,-0.917815,-0.188427,-0.005379,-0.020505,-0.005238,-0.064965,...,0.323695,0.556357,0.533484,-0.259915,-1.093415,-0.1623,-0.254146,-0.252326,-0.414249,-0.408892
311028,-0.078388,2.232618,1.428547,0.47954,-0.917815,-0.188427,-0.005379,-0.020505,-0.005238,-0.064965,...,0.323695,0.556357,0.533484,-0.259915,-1.093415,-0.1623,-0.254146,-0.252326,-0.414249,-0.408892

In [25]:
len(x_train)

494021

In [26]:
from sklearn.linear_model import LogisticRegression

model_LR = LogisticRegression()
model_LR.fit(x_train, y_train)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\linear_model\logistic.py:459: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [27]:
# make predictions
expected = y_test
predicted = model_LR.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.9204286417022207

In [28]:

# fit a Naive Bayes model to the data
model_gaussian = GaussianNB()
model_gaussian.fit(x_train, y_train)
print(model_gaussian)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB(priors=None, var_smoothing=1e-09)

In [29]:
# make predictions
expected = y_test
predicted = model_gaussian.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.19494002167000504

In [31]:
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(x_train, y_train)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [32]:
# make predictions
expected = y_test
predicted = model.predict(x_test)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.9225409849242353

In [34]:

model_DTC = DecisionTreeClassifier()
model_DTC.fit(x_train, y_train)
print(model_DTC)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [35]:
# make predictions
expected = y_test
predicted = model_DTC.predict(x_test)

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.9077995942500539

In [37]:

model_Ada = AdaBoostClassifier(n_estimators=100)
model_Ada.fit(x_train, y_train)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\sklearn\utils\validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=100, random_state=None)

In [38]:
# make predictions
expected = y_test
predicted = model_DTC.predict(x_test)

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.9077995942500539

In [40]:
model_R = RandomForestClassifier(n_estimators=500)
model_R = model_R.fit(x_train, y_train)

C:\Users\hassan\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [41]:
# make predictions
expected = y_test
predicted = model_R.predict(x_test)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.9180751634091998